version: '3.4'

services:
  tiendaservicios.api.autor:
    image: tiendaserviciosapiautor:dev
    container_name: TiendaServicios.Api.Autor
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TiendaServicios.Api.Autor"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_tiendaservicios.api.autor$
    volumes:
      - Z:\PROGRAMACION\C#\.NETCORE\TiendaServicios\TiendaServicios.Api.Autor:/app
      - Z:\PROGRAMACION\C#\.NETCORE\TiendaServicios:/src
      - C:\Users\gerol\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_tiendaservicios.api.autor$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_tiendaservicios.api.autor$ \"/app/bin/Debug/netcoreapp3.1/TiendaServicios.Api.Autor.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true